TDLR-2550 - new rake task to update Collections, adding finding aid l…
TuftsUniversity/mira_on_hyrax pull request #103
Opened 2024-04-01 16:22 UTC by bgoodmon

…ink and call number.

2024-04-23 14:58 UTC, mkorcy requested changes
brian and i discussed on zoom

2024-04-23 14:58 UTC, mkorcy commented on lib/tasks/add_collection_fa_cn.rake
> +# frozen_string_literal: true
fa_cn?

2024-04-23 14:58 UTC, mkorcy commented on lib/tasks/add_collection_fa_cn.rake
> +      collection = collections.nil? ? nil : collections.first
collections.nil? doesn't make sensse collections.empty? would be a better check of an array, and then you wouldn't call collections.first.

2024-04-23 14:58 UTC, mkorcy commented on lib/tasks/add_collection_fa_cn.rake
> +      collections = Collection.where(title: "Foobar")
make this a real collection

2024-04-24 22:29 UTC, bgoodmon commented on lib/tasks/add_collection_fa_cn.rake
> +# frozen_string_literal: true
Finding Aid (url) and Call Number

2024-04-24 22:34 UTC, bgoodmon commented on lib/tasks/add_collection_fa_cn.rake
> +      collection = collections.nil? ? nil : collections.first
I changed this to just call collections.first.  collections isn't an array, it's an ActiveFedora::Relation.  When the rake task is run it prints the following warning when collections.first is called, even if collections.empty? is true:
DEPRECATION: Rsolr.new/connect option `read_timeout` is deprecated and will be removed in Rsolr 3. `timeout` is currently a synonym, use that instead.

2024-04-24 22:36 UTC, bgoodmon commented on lib/tasks/add_collection_fa_cn.rake
> +      collection = collections.nil? ? nil : collections.first
The whole point of this block of code is simply to cause that warning to be printed at the top of the output with all the other warnings so that all the warnings are printed before any of the actual output of the task is printed.
I changed the comments to make this more clear.

2024-04-24 22:39 UTC, bgoodmon commented on lib/tasks/add_collection_fa_cn.rake
> +      collections = Collection.where(title: "Foobar")
It doesn't matter whether it's a real collection or not;  the ActiveFedora::Relation causes the deprecation warning even if the Collection is not found and the ActiveFedora::Relation is empty.

Something I don't understand is that if you're in the rails console playing around with this, the deprecation warning happens when you call Collection.where(), but in the actual rake task it doesn't happen until you call Collection.first().  I proved this to myself several times.

2024-04-24 22:40 UTC, bgoodmon commented on lib/tasks/add_collection_fa_cn.rake
> +      collections = Collection.where(title: "Foobar")
This is pushed on my branch and tests passed.  I'll rebase and push again after you approve.

2024-04-25 14:55 UTC, mkorcy approved these changes

2024-04-25 18:23 UTC, merged