TBW
TuftsUniversity/mira_on_hyrax pull request #59
Opened 2022-10-11 19:50 UTC by rawOrlando

Rspec: Metadata Form and Metadata Attributes specs are missing some fields, add coverage.

https://tuftswork.atlassian.net/browse/TDLR-2422

2022-10-14 17:53 UTC, rawOrlando commented
A couple of attributes I am stuck on:
- [ ] doi (Descriptive)
- [ ] aspace_cuid (Administrative)
- [ ] date_modified (Technical)
- [ ] identifier (Technical)
- [ ] date_uploaded
- [ ] language

Gonna circle back to these.

2022-10-21 18:39 UTC, rawOrlando commented
@mkorcy forgot to mark this for review. But I think this is all good. and since the tests pass that's a fine sign it works.

2022-10-24 19:13 UTC, mkorcy requested changes
@rawOrlando -- Thanks this is some good clean up, and captures the missing fields.  In the technical metadata `date_modified` appears twice, one should get removed.  I put some other comments in for some small changes to make the output read more consistently, rare that we read it line by line just stuff that's probably been like that for a while.

2022-10-24 19:13 UTC, mkorcy commented on spec/support/shared_examples/metadata_attributes/technical_metadata.rb
> +
`date_modified` appears twice.

2022-10-24 19:13 UTC, mkorcy commented on spec/support/shared_examples/metadata_form.rb
> +                                    :tufts_license)
Thanks for alphabetizing these!

2022-10-24 19:13 UTC, mkorcy commented on spec/support/shared_examples/metadata_attributes/metadata_attribute.rb
> +  it_behaves_like 'and has technical metadata attributes'
not a deal breaker but it makes it would probably output in `rspec` a little cleaner if the sentences didn't start with `and`. I get why you went with that given the nesting but what it actually outputs is like:

```
 Tei
 ...
  behaves like a work with Tufts metadata attributes
    behaves like a work with custom Tufts validations
      only has one title
    behaves like and has admin metadata attributes
      has legacy pid
      has held by
      ...
    behaves like and has technical metadata attributes
      has date_modified
      has date_modified
```

2022-10-24 19:13 UTC, mkorcy commented on spec/support/shared_examples/metadata_attributes/descriptive_metadata.rb
> +  it 'has "is replaced by"' do
for consistency can you remove the inner quotes and change to is_replaced_by

2022-10-24 19:13 UTC, mkorcy commented on spec/support/shared_examples/metadata_attributes/descriptive_metadata.rb
> +  it 'has "has part"' do
for consistency can you remove the inner quotes and change to has_part

2022-10-24 19:13 UTC, mkorcy commented on spec/support/shared_examples/metadata_attributes/admin_metadata.rb
> +  end
not your fault, but as long as you're here can you change `createdby` to `has createdby` and `is part of` to `has is_part_of`

2022-10-26 19:25 UTC, rawOrlando commented
@mkorcy this should be all good now.

2022-10-27 16:21 UTC, mkorcy approved these changes
Looks good, thanks for making the updates.

2022-10-27 16:55 UTC, merged