Shib set up
TuftsUniversity/mira_on_hyrax pull request #91
Opened 2023-03-29 23:22 UTC by rawOrlando

tbd

2023-04-05 17:03 UTC, rawOrlando commented
Need to follow #90 to set up mod_shib and shibd before this work.

2023-04-07 18:23 UTC, mkorcy requested changes
A few small changes, this can't go to prod today anyway.  I'd need TARC/Tisch to sign off Authentication method changing is sort of a big change, and April is a busy time for self-deposit as the Spring semester winds down and people are trying to deposit to comply with degree requirements for graduation.

2023-04-07 18:23 UTC, mkorcy commented on app/views/contribute/index.html.erb
> -      <p><a href="http://uit.tufts.edu/?pid=744">Tufts Simplified Sign-On Enabled</a></p>
Thanks for cleaning up the simplified sign-on messaging.

2023-04-07 18:23 UTC, mkorcy commented on config/initializers/devise.rb
> +  end
We should test this with someone who has no prior MIRA account to make sure roles get assigned correctly, I'll ask Ian to login on dev.

2023-04-07 18:23 UTC, mkorcy commented on .github/workflows/ci.yml
> +      # DATABASE_AUTH: true
Did you make this change, because you saw me make in TDL or is this something else? I'm blanking on what this does.

2023-04-07 18:23 UTC, mkorcy commented on app/controllers/omniauthcallbacks_controller.rb
> +    # Rails.logger.warn "request2 = #{auth.inspect}"
24L-26L can be deleted, I should've cleaned that up in TDL too.  The other stuff may as well leave if we have to debug a shib problem it'll be useful rather than trying to figure out what to capture.

2023-04-07 18:23 UTC, mkorcy commented on app/models/user.rb
> +    # #devise_modules.prepend(:database_authenticatable) if AuthConfig.use_database_auth?
this line can get axed.

2023-04-11 13:57 UTC, rawOrlando commented on .github/workflows/ci.yml
> +      # DATABASE_AUTH: true
turns out I did not need this change.

2023-04-11 13:57 UTC, rawOrlando commented on config/initializers/devise.rb
> +  end
Have you asked Ian? if not which one?

2023-04-11 13:58 UTC, rawOrlando commented
@mkorcy, can you look over the cleanup and give a Thumbs up before you leave for your vacation.

2023-04-11 14:01 UTC, mkorcy commented
@rawOrlando yeah.  will do. Didn't ask Ian he's on vacation, let me grab someone else.

2023-04-11 22:47 UTC, merged